# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[edge_functions]]
  function = "geolocation"
  path = "/api/geolocation"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev" # Command to start your dev server
  port = 3000             # Port that the dev server will be listening on
  publish = "dist"        # Folder with the static content for _redirect file
  framework = "vite"      # Framework to use for auto-detection, see https://ntl.fyi/dev-frameworks
  targetPort = 5173       # Port that Netlify Dev will run on

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config

